Resources:
  searchEngineDb:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: 'mysql'
      DBInstanceIdentifier: 'searchEngineDb'
      MasterUsername: 'admin'
      MasterUserPassword: '123456789'
      AllocatedStorage: 20
      DBInstanceClass: db.t4g.small
      AvailabilityZone: 'us-east-2a'
      DBName: 'searchEngineDb'